export class Controls {
	constructor() {
		this.keys = {}; this.x = 0; this.z = 0; this.touchActive = false; this.touchDirX = 0; this.touchDirY = 0;
		this.steerPointerId = null; this.steerStartX = 0; this.steerStartY = 0; this.btnUp = false; this.btnDown = false; this.btnHandbrake = false;
		this.gyroSupported = 'DeviceOrientationEvent' in window; this.gyroEnabled = false; this.gyroCalibrated = false; this.gyroCenter = 0; this.gyroAngle = 0; this.gyroSteer = 0;
		this.gyroDeadZone = 2.5; this.gyroMaxAngle = 28; this.gyroSmoothing = 0.18; this.gyroButton = null;
		this._onDeviceOrientation = e => this.handleDeviceOrientation( e );
		window.addEventListener( 'keydown', e => this.keys[ e.code ] = true );
		window.addEventListener( 'keyup', e => this.keys[ e.code ] = false );
	}
	getScreenAngle(){if(screen.orientation&&Number.isFinite(screen.orientation.angle))return screen.orientation.angle;if(Number.isFinite(window.orientation))return window.orientation;return 0}
	getTiltAngle(beta,gamma){const a=((this.getScreenAngle()%360)+360)%360;if(a===90)return beta;if(a===270)return-beta;if(a===180)return-gamma;return gamma}
	handleDeviceOrientation(e){if(!this.gyroEnabled||!Number.isFinite(e.beta)||!Number.isFinite(e.gamma))return;const angle=this.getTiltAngle(e.beta,e.gamma);this.gyroAngle=angle;if(!this.gyroCalibrated){this.gyroCenter=angle;this.gyroCalibrated=true;this.gyroSteer=0;return}let delta=angle-this.gyroCenter;if(Math.abs(delta)<=this.gyroDeadZone)delta=0;else delta-=Math.sign(delta)*this.gyroDeadZone;const range=Math.max(1,this.gyroMaxAngle-this.gyroDeadZone),target=Math.max(-1,Math.min(1,delta/range));this.gyroSteer+=(target-this.gyroSteer)*this.gyroSmoothing}
	calibrateGyro(){this.gyroCenter=this.gyroAngle;this.gyroCalibrated=true;this.gyroSteer=0}
	async enableGyro(){if(!this.gyroSupported)return false;try{if(typeof DeviceOrientationEvent.requestPermission==='function'){const p=await DeviceOrientationEvent.requestPermission();if(p!=='granted')return false}if(!this.gyroEnabled){window.addEventListener('deviceorientation',this._onDeviceOrientation,true);this.gyroEnabled=true;this.gyroCalibrated=false;this.gyroSteer=0}return true}catch(error){console.warn('Gyro steering could not be enabled:',error);return false}}
	setupTouchUI(){
		if(!('ontouchstart'in window))return;
		const css=document.createElement('style');css.textContent=`.touch-controls{position:absolute;inset:0;pointer-events:none;z-index:100}.steer-zone{position:absolute;inset:0;pointer-events:auto;touch-action:none}.steer-base{position:absolute;width:140px;height:140px;margin:-70px 0 0 -70px;border-radius:50%;background:rgba(255,255,255,.1);border:2px solid rgba(255,255,255,.2);display:none}.steer-knob{position:absolute;top:50%;left:50%;width:60px;height:60px;margin:-30px 0 0 -30px;border-radius:50%;background:rgba(255,255,255,.35)}.drive-buttons{position:absolute;inset:0;pointer-events:none;z-index:3}.drive-btn{position:absolute;bottom:max(18px,env(safe-area-inset-bottom));width:84px;height:84px;border:2px solid rgba(255,255,255,.35);border-radius:50%;background:rgba(0,0,0,.38);color:#fff;font:700 13px/1 sans-serif;touch-action:none;user-select:none;pointer-events:auto}.drive-btn.brake{left:max(18px,env(safe-area-inset-left))}.drive-btn.gas{right:max(18px,env(safe-area-inset-right))}.drive-btn.handbrake{left:50%;transform:translateX(-50%);width:96px;height:58px;border-radius:22px;bottom:max(28px,env(safe-area-inset-bottom));font-size:12px}.drive-btn.active{background:rgba(255,255,255,.3)}.gyro-controls{position:absolute;left:50%;top:max(14px,env(safe-area-inset-top));transform:translateX(-50%);display:flex;gap:8px;pointer-events:auto;z-index:3}.gyro-btn{min-width:82px;height:38px;padding:0 12px;border:1px solid rgba(255,255,255,.35);border-radius:18px;background:rgba(0,0,0,.48);color:#fff;font:700 12px/1 sans-serif}.gyro-btn.enabled{background:rgba(28,110,54,.72)}`;document.head.appendChild(css);
		const container=document.createElement('div');container.className='touch-controls';const steerZone=document.createElement('div');steerZone.className='steer-zone';const base=document.createElement('div');base.className='steer-base';const knob=document.createElement('div');knob.className='steer-knob';base.appendChild(knob);steerZone.appendChild(base);
		const driveButtons=document.createElement('div');driveButtons.className='drive-buttons';const brakeBtn=document.createElement('button');brakeBtn.className='drive-btn brake';brakeBtn.textContent='BRAKE';const gasBtn=document.createElement('button');gasBtn.className='drive-btn gas';gasBtn.textContent='GAS';const handbrakeBtn=document.createElement('button');handbrakeBtn.className='drive-btn handbrake';handbrakeBtn.textContent='HANDBRAKE';driveButtons.append(brakeBtn,gasBtn,handbrakeBtn);
		const gyroControls=document.createElement('div');gyroControls.className='gyro-controls';const gyroBtn=document.createElement('button');gyroBtn.className='gyro-btn';gyroBtn.textContent=this.gyroSupported?'GYRO':'NO GYRO';gyroBtn.disabled=!this.gyroSupported;this.gyroButton=gyroBtn;const calibrateBtn=document.createElement('button');calibrateBtn.className='gyro-btn';calibrateBtn.textContent='CENTER';calibrateBtn.disabled=true;gyroControls.append(gyroBtn,calibrateBtn);container.append(steerZone,driveButtons,gyroControls);document.body.appendChild(container);
		const bind=(button,property)=>{const press=e=>{e.preventDefault();e.stopPropagation();this[property]=true;button.classList.add('active');button.setPointerCapture?.(e.pointerId)};const release=e=>{e.preventDefault();e.stopPropagation();this[property]=false;button.classList.remove('active')};button.addEventListener('pointerdown',press);button.addEventListener('pointerup',release);button.addEventListener('pointercancel',release);button.addEventListener('lostpointercapture',()=>{this[property]=false;button.classList.remove('active')})};bind(gasBtn,'btnUp');bind(brakeBtn,'btnDown');bind(handbrakeBtn,'btnHandbrake');
		gyroBtn.addEventListener('click',async e=>{e.preventDefault();e.stopPropagation();if(this.gyroEnabled){this.calibrateGyro();gyroBtn.textContent='GYRO ON';return}const enabled=await this.enableGyro();if(enabled){gyroBtn.textContent='GYRO ON';gyroBtn.classList.add('enabled');calibrateBtn.disabled=false;base.style.display='none'}else gyroBtn.textContent='GYRO BLOCKED'});calibrateBtn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();this.calibrateGyro()});
		const range=40;steerZone.addEventListener('pointerdown',e=>{if(this.gyroEnabled||this.steerPointerId!==null)return;steerZone.setPointerCapture(e.pointerId);this.steerPointerId=e.pointerId;this.steerStartX=e.clientX;this.steerStartY=e.clientY;this.touchActive=true;this.touchDirX=0;this.touchDirY=0;base.style.left=`${e.clientX}px`;base.style.top=`${e.clientY}px`;base.style.display='block'});steerZone.addEventListener('pointermove',e=>{if(this.gyroEnabled||e.pointerId!==this.steerPointerId)return;let dx=(e.clientX-this.steerStartX)/range,dy=(e.clientY-this.steerStartY)/range;const mag=Math.hypot(dx,dy);if(mag>1){dx/=mag;dy/=mag}this.touchDirX=dx;this.touchDirY=dy;knob.style.transform=`translate(${dx*60}px,${dy*60}px)`});const end=e=>{if(e.pointerId!==this.steerPointerId)return;this.steerPointerId=null;this.touchActive=false;this.touchDirX=0;this.touchDirY=0;knob.style.transform='';base.style.display='none'};steerZone.addEventListener('pointerup',end);steerZone.addEventListener('pointercancel',end);
	}
	update(){
		let x=0,z=0,handbrake=!!this.keys.Space;if(this.keys.KeyA||this.keys.ArrowLeft)x-=1;if(this.keys.KeyD||this.keys.ArrowRight)x+=1;if(this.keys.KeyW||this.keys.ArrowUp)z+=1;if(this.keys.KeyS||this.keys.ArrowDown)z-=1;
		const gamepads=navigator.getGamepads?navigator.getGamepads():[];for(const gp of gamepads){if(!gp)continue;const sx1=gp.axes[0]||0,sx2=gp.axes[2]||0,sx=Math.abs(sx1)>Math.abs(sx2)?sx1:sx2;if(Math.abs(sx)>.15)x=sx;const r=gp.buttons[7]?gp.buttons[7].value:(gp.buttons[0]?.value||0),l=gp.buttons[6]?gp.buttons[6].value:(gp.buttons[1]?.value||0);if(r>.1||l>.1)z=r-l;else{const sy1=gp.axes[1]||0,sy2=gp.axes[3]||0,sy=Math.abs(sy1)>Math.abs(sy2)?sy1:sy2;if(Math.abs(sy)>.15)z=-sy}if(gp.buttons[1]?.pressed||gp.buttons[4]?.pressed)handbrake=true;if(Math.abs(x)>.05||Math.abs(z)>.05||handbrake)break}
		if(this.gyroEnabled){x=this.gyroSteer;if(this.btnUp&&!this.btnDown)z=1;else if(this.btnDown&&!this.btnUp)z=-1;else if(this.btnUp&&this.btnDown)z=0}else if(this.touchActive){const jx=this.touchDirX,jy=this.touchDirY,mag=Math.hypot(jx,jy);if(mag>.15){x=(jx+jy)*Math.SQRT1_2/mag;z=(-jx+jy)*Math.SQRT1_2/mag}}
		if(this.btnUp&&!this.btnDown)z=1;else if(this.btnDown&&!this.btnUp)z=-1;else if(this.btnUp&&this.btnDown)z=0;if(this.btnHandbrake)handbrake=true;this.x=x;this.z=z;const mobile=this.touchActive||this.btnUp||this.btnDown||this.btnHandbrake||(this.gyroEnabled&&Math.abs(this.gyroSteer)>.05);return{x,z,touchActive:mobile,handbrake};
	}
}
