import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { LightProbeGrid } from 'three/addons/lighting/LightProbeGrid.js';
import { createWorldSettings, createWorld, addBroadphaseLayer, addObjectLayer, enableCollision, registerAll, updateWorld, rigidBody, box, MotionType } from 'crashcat';
import { Vehicle, MAX_SPEED } from './Vehicle.js';
import { Camera } from './Camera.js';
import { Controls } from './Controls.js';
import { buildTrack, decodeCells, computeSpawnPosition, computeTrackBounds, TRACK_CELLS } from './Track.js';
import { buildWallColliders, createSphereBody } from './Physics.js';
import { SmokeTrails } from './Particles.js';
import { DriftMarks } from './DriftMarks.js';
import { GameAudio } from './Audio.js';
import { LapTimer } from './LapTimer.js';
import { ARManager } from './ARManager.js';
import { ColorMapGLTFLoader } from './Loader.js';
import { buildDriftArena, buildDriftArenaPhysics, DRIFT_ARENA_RADIUS } from './DriftArena.js';
import { ARModeMenu } from './ARModeMenu.js';
import { createArenaAI, updateArenaAI } from './ArenaAI.js';

const pageParams = new URLSearchParams( window.location.search );
const requestedARMode = pageParams.get( 'arMode' );
const homeARHost = document.body.dataset.homeArHost === 'true';
const initialARMode = homeARHost ? 'menu' : ( [ 'free', 'track', 'arena' ].includes( requestedARMode ) ? requestedARMode : 'free' );
const isARExperience = homeARHost || pageParams.get( 'ar' ) === '1';
const requestedWebMode = pageParams.get( 'mode' );
const webMode = requestedWebMode === 'arena' ? 'arena' : 'track';
const isWebArena = ! isARExperience && webMode === 'arena';
const AR_CONTENT_SCALE = 0.08;
const AR_VEHICLE_RADIUS = 0.5 * AR_CONTENT_SCALE;
let activeARMode = initialARMode;
let selectedCharacter = 'vehicle';
try { selectedCharacter = window.localStorage.getItem( 'drifting-character' ) === 'road_runner' ? 'road_runner' : 'vehicle'; } catch ( e ) {}

const renderer = new THREE.WebGLRenderer( { antialias: true, outputBufferType: THREE.HalfFloatType, alpha: true } );
renderer.xr.enabled = true;
const xrBtnStyle = document.createElement( 'style' );
xrBtnStyle.textContent = `#ARButton{position:absolute!important;bottom:20px!important;left:50%!important;transform:translateX(-50%)!important;z-index:10000!important;padding:12px 24px!important;font-size:16px!important;font-weight:bold!important;border-radius:30px!important;border:none!important;background:rgba(0,0,0,.7)!important;color:#fff!important;display:none}#ARButton[data-supported="true"]{display:block!important}#ARButton:disabled{opacity:.5!important}#WebModeButton{position:absolute;top:max(14px,env(safe-area-inset-top));right:max(14px,env(safe-area-inset-right));z-index:120;padding:10px 15px;border:1px solid rgba(255,255,255,.38);border-radius:20px;background:rgba(0,0,0,.52);color:#fff;font:700 12px/1 sans-serif}`;
document.head.appendChild( xrBtnStyle );
renderer.setSize( window.innerWidth, window.innerHeight ); renderer.setPixelRatio( window.devicePixelRatio ); renderer.shadowMap.enabled = true; renderer.toneMapping = THREE.ACESFilmicToneMapping; renderer.toneMappingExposure = 1;
let composer = null, arManager = null, arEnterBtn = null, arSessionPending = false;
async function enterAR(){if(!arManager||arSessionPending)return;arSessionPending=true;arEnterBtn.disabled=true;arEnterBtn.textContent='STARTING AR…';try{await arManager.requestSession()}catch(error){console.error('[AR] Unable to start immersive-ar session:',error);arEnterBtn.textContent='ENTER AR';arEnterBtn.disabled=false}finally{arSessionPending=false}}
window.startDriftingAR=enterAR;
function setupDOM(){if(!document.body.contains(renderer.domElement))document.body.appendChild(renderer.domElement);arEnterBtn=document.createElement('button');arEnterBtn.id='ARButton';arEnterBtn.textContent='ENTER AR';arEnterBtn.disabled=true;arEnterBtn.addEventListener('click',()=>enterAR());document.body.appendChild(arEnterBtn);if(!isARExperience){const b=document.createElement('button');b.id='WebModeButton';b.textContent=isWebArena?'TRACK':'ARENA';b.addEventListener('click',e=>{e.preventDefault();const p=new URLSearchParams(window.location.search);p.set('mode',isWebArena?'track':'arena');window.location.search=p.toString()});document.body.appendChild(b)}ARManager.isSupported().then(s=>{arEnterBtn.dataset.supported=s&&isARExperience&&!homeARHost?'true':'false'})}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',setupDOM);else setupDOM();

const scene=new THREE.Scene();scene.background=new THREE.Color(0xadb2ba);scene.fog=new THREE.Fog(0xadb2ba,30,55);const dirLight=new THREE.DirectionalLight(0xffffff,3);dirLight.position.set(11.4,15,-5.3);dirLight.castShadow=true;dirLight.shadow.mapSize.setScalar(4096);dirLight.shadow.camera.near=.5;dirLight.shadow.camera.far=60;scene.add(dirLight);const hemiLight=new THREE.HemisphereLight(0xc8d8e8,0x7a8a5a,2);scene.add(hemiLight);window.addEventListener('resize',()=>{renderer.setSize(window.innerWidth,window.innerHeight);composer?.setSize(window.innerWidth,window.innerHeight)});
const loader=new ColorMapGLTFLoader();const modelNames=['vehicle-truck-yellow','vehicle-truck-green','vehicle-truck-purple','vehicle-truck-red','road_runner','track-straight','track-corner','track-bump','track-finish','decoration-empty','decoration-forest','decoration-tents'];const models={};
async function loadModels(){const names=isARExperience?modelNames.filter(n=>!n.startsWith('decoration-')):modelNames;await Promise.all(names.map(name=>new Promise((resolve,reject)=>loader.load(`models/${name}.glb`,gltf=>{const meshes=[];gltf.scene.traverse(child=>{if(child.isMesh){child.material.side=THREE.FrontSide;meshes.push(child)}});if(name.startsWith('vehicle-'))gltf.scene.scale.setScalar(.5);if(meshes.length===1){const mesh=meshes[0];mesh.removeFromParent();models[name]=mesh}else models[name]=gltf.scene;resolve()},undefined,reject))))}

async function init(){
	registerAll(); await loadModels(); const mapParam=pageParams.get('map'); let customCells=null,spawn=null; if(mapParam){try{customCells=decodeCells(mapParam);spawn=computeSpawnPosition(customCells)}catch(e){}}
	const bounds=computeTrackBounds(customCells),arTrackBounds=computeTrackBounds(customCells||TRACK_CELLS),hw=bounds.halfWidth,hd=bounds.halfDepth,groundSize=Math.max(hw,hd)*2+20;const shadowExtent=isWebArena?DRIFT_ARENA_RADIUS+8:Math.max(hw,hd)+10;dirLight.shadow.camera.left=-shadowExtent;dirLight.shadow.camera.right=shadowExtent;dirLight.shadow.camera.top=shadowExtent;dirLight.shadow.camera.bottom=-shadowExtent;dirLight.shadow.camera.updateProjectionMatrix();scene.fog.near=isWebArena?24:groundSize*.4;scene.fog.far=isWebArena?70:groundSize*.8;
	const trackGroup=buildTrack(scene,models,customCells,!isARExperience);trackGroup.visible=!isARExperience&&!isWebArena;if(isARExperience)trackGroup.scale.multiplyScalar(AR_CONTENT_SCALE);const driftArenaGroup=buildDriftArena(models);driftArenaGroup.visible=isWebArena;if(isARExperience)driftArenaGroup.scale.setScalar(AR_CONTENT_SCALE);scene.add(driftArenaGroup);
	if(!isARExperience&&!isWebArena){try{const probes=new LightProbeGrid(hw*2,6,hd*2,Math.max(4,Math.round(hw/4)),2,Math.max(4,Math.round(hd/4)));probes.position.set(bounds.centerX,3,bounds.centerZ);probes.bake(renderer,scene,{cubemapSize:32,near:.1,far:groundSize});scene.add(probes)}catch(e){}}
	const ws=createWorldSettings();ws.gravity=[0,-9.81,0];const bm=addBroadphaseLayer(ws),bs=addBroadphaseLayer(ws),om=addObjectLayer(ws,bm),os=addObjectLayer(ws,bs);enableCollision(ws,om,os);enableCollision(ws,om,om);const world=createWorld(ws);world._OL_MOVING=om;world._OL_STATIC=os;const roadHalf=groundSize/2;if(!isARExperience){if(isWebArena)buildDriftArenaPhysics(world,new THREE.Vector3(),1);else{buildWallColliders(world,null,customCells);rigidBody.create(world,{shape:box.create({halfExtents:[roadHalf,.01,roadHalf]}),motionType:MotionType.STATIC,objectLayer:os,position:[bounds.centerX,-.125,bounds.centerZ],friction:5,restitution:0})}}
	const webArenaSpawn=[0,.5,DRIFT_ARENA_RADIUS*.45],initialSpawn=isWebArena?webArenaSpawn:(spawn?spawn.position:null),sphereBody=createSphereBody(world,initialSpawn,isARExperience?AR_VEHICLE_RADIUS:.5);const vehicle=new Vehicle();vehicle.rigidBody=sphereBody;vehicle.physicsWorld=world;vehicle.visualOffset=isARExperience?AR_VEHICLE_RADIUS:.5;vehicle.sphereRadius=vehicle.visualOffset;if(isWebArena){vehicle.spawnPos.set(...webArenaSpawn);vehicle.spawnAngle=Math.PI;vehicle.spherePos.set(...webArenaSpawn);vehicle.prevModelPos.set(webArenaSpawn[0],0,webArenaSpawn[2]);vehicle.container.rotation.y=Math.PI}else if(spawn){const[sx,sy,sz]=spawn.position;vehicle.spawnPos.set(sx,sy,sz);vehicle.spawnAngle=spawn.angle;vehicle.spherePos.set(sx,sy,sz);vehicle.prevModelPos.set(sx,0,sz);vehicle.container.rotation.y=spawn.angle}
	const arGroup=new THREE.Group();scene.add(arGroup);const toMove=[];scene.children.forEach(c=>{if(c!==dirLight&&c!==hemiLight&&c!==arGroup)toMove.push(c)});toMove.forEach(c=>arGroup.add(c));const modeMenu=new ARModeMenu(scene),webEnvironmentVisibility=new Map();
	renderer.xr.addEventListener('sessionstart',()=>{toMove.forEach(o=>{webEnvironmentVisibility.set(o,o.visible);o.visible=false});if(activeARMode==='menu'){modeMenu.show();arManager.setSelectionRaysVisible(true)}});renderer.xr.addEventListener('sessionend',()=>{toMove.forEach(o=>o.visible=webEnvironmentVisibility.get(o)??true);webEnvironmentVisibility.clear();modeMenu.hide();arManager.setSelectionRaysVisible(false);if(homeARHost){activeARMode='menu';arManager.buildFreeRoamFloor=false;arManager.setPlacementEnabled(false);setTimeout(()=>location.reload(),50)}});
	let arVehicleScaleFactor=1,vehicleGroup=vehicle.init(models['vehicle-truck-yellow']),roadRunnerVisual=null;if(models.road_runner){roadRunnerVisual=models.road_runner.clone();roadRunnerVisual.name='road-runner-free-ar';roadRunnerVisual.scale.setScalar(.55);roadRunnerVisual.visible=false;roadRunnerVisual.traverse(child=>{if(child.isMesh){child.castShadow=true;child.receiveShadow=true}});vehicleGroup.add(roadRunnerVisual)}const syncCharacterVisual=()=>{if(!roadRunnerVisual)return;const use=selectedCharacter==='road_runner';vehicleGroup.children.forEach(child=>{if(child!==roadRunnerVisual)child.visible=!use});roadRunnerVisual.visible=use};if(isARExperience)vehicleGroup.scale.setScalar(AR_CONTENT_SCALE*arVehicleScaleFactor);syncCharacterVisual();arGroup.add(vehicleGroup);dirLight.target=vehicleGroup;
	let arenaAIDrivers=[];if(isWebArena)arenaAIDrivers=createArenaAI({world,parent:arGroup,models,center:new THREE.Vector3(0,0,0),scale:1,count:3});
	arManager=new ARManager({renderer,scene,buildFreeRoamFloor:activeARMode==='free',placementEnabled:activeARMode!=='menu',spawnHeight:isARExperience?AR_VEHICLE_RADIUS:.5});arManager.setWorld(world);arManager.onPlaced=({position,angle})=>{let vp=position.clone(),va=angle;if(activeARMode==='track'){const offset={x:position.x-arTrackBounds.centerX*AR_CONTENT_SCALE,y:position.y,z:position.z-arTrackBounds.centerZ*AR_CONTENT_SCALE,scale:AR_CONTENT_SCALE};trackGroup.position.set(offset.x,position.y-.5*.75*AR_CONTENT_SCALE,offset.z);trackGroup.visible=true;buildWallColliders(world,null,customCells,offset);rigidBody.create(world,{shape:box.create({halfExtents:[roadHalf*AR_CONTENT_SCALE,.01*AR_CONTENT_SCALE,roadHalf*AR_CONTENT_SCALE]}),motionType:MotionType.STATIC,objectLayer:os,position:[position.x,position.y-.01*AR_CONTENT_SCALE,position.z],friction:5,restitution:0});const ts=spawn||computeSpawnPosition(TRACK_CELLS);vp.set(ts.position[0]*AR_CONTENT_SCALE+offset.x,position.y+AR_VEHICLE_RADIUS,ts.position[2]*AR_CONTENT_SCALE+offset.z);va=ts.angle}else if(activeARMode==='arena'){driftArenaGroup.position.copy(position);driftArenaGroup.visible=true;buildDriftArenaPhysics(world,position,AR_CONTENT_SCALE);vp.set(position.x,position.y+AR_VEHICLE_RADIUS,position.z+DRIFT_ARENA_RADIUS*AR_CONTENT_SCALE*.45);va=Math.PI;if(arenaAIDrivers.length===0)arenaAIDrivers=createArenaAI({world,parent:arGroup,models,center:position,scale:AR_CONTENT_SCALE,count:3})}rigidBody.setPosition(world,sphereBody,[vp.x,vp.y,vp.z],false);rigidBody.setLinearVelocity(world,sphereBody,[0,0,0]);rigidBody.setAngularVelocity(world,sphereBody,[0,0,0]);vehicle.spherePos.copy(vp);vehicle.spawnPos.copy(vp);vehicle.spawnAngle=va;vehicle.sphereVel.set(0,0,0);vehicle.prevModelPos.set(vp.x,vp.y-vehicle.visualOffset,vp.z);vehicle.linearSpeed=0;vehicle.angularSpeed=0;vehicle.container.quaternion.setFromAxisAngle(new THREE.Vector3(0,1,0),va)};
	if(arEnterBtn)arEnterBtn.disabled=false;if(homeARHost){const supported=await ARManager.isSupported();window.dispatchEvent(new CustomEvent('drifting-ar-ready',{detail:{supported}}))}
	const cam=new Camera();scene.add(cam.debug);try{composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,cam.camera));composer.addPass(new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),.02,.02,.5))}catch(e){}const controls=new Controls();if(!homeARHost)controls.setupTouchUI();const particles=new SmokeTrails(scene,isARExperience?{poolSize:160,particlesPerEmit:1,scale:AR_CONTENT_SCALE,maxLife:1.1,emitInterval:.1}:undefined);const driftMarks=new DriftMarks(scene,mapParam,{persist:!isARExperience});const audio=new GameAudio();audio.init(cam.camera,vehicleGroup);const lapTimer=homeARHost||isWebArena?null:new LapTimer(customCells,mapParam);const _forward=new THREE.Vector3(),_camLead=new THREE.Vector3();const contactListener={onContactAdded(a,b){if(a!==sphereBody&&b!==sphereBody)return;_forward.set(0,0,1).applyQuaternion(vehicle.container.quaternion);_forward.y=0;_forward.normalize();audio.playImpact(Math.abs(vehicle.modelVelocity.dot(_forward)))}};const timer=new THREE.Timer();
	renderer.setAnimationLoop((timestamp,frame)=>{timer.update();const dt=Math.min(timer.getDelta(),1/30),inAR=renderer.xr.isPresenting;if(inAR&&frame){if(activeARMode==='menu'){modeMenu.placeInFrontOf(renderer.xr.getCamera());const selectedMode=modeMenu.update(arManager.controllers,arManager.gamepads);if(selectedMode){activeARMode=selectedMode;syncCharacterVisual();if(activeARMode==='free'){arVehicleScaleFactor=Math.max(arVehicleScaleFactor,1.5);vehicleGroup.scale.setScalar(AR_CONTENT_SCALE*arVehicleScaleFactor)}modeMenu.hide();arManager.setSelectionRaysVisible(false);arManager.buildFreeRoamFloor=activeARMode==='free';arManager.setPlacementEnabled(true)}}arManager.update(frame,dt)}let input;if(inAR)input=arManager.isPlaced()?arManager.getDriveInput():{x:0,z:0,touchActive:false,handbrake:false};else input=controls.update();if(inAR&&arManager.isPlaced()&&activeARMode==='free'){const s=arManager.getVehicleScaleInput();if(s!==0){arVehicleScaleFactor=THREE.MathUtils.clamp(arVehicleScaleFactor+s*dt,.5,2.5);vehicleGroup.scale.setScalar(AR_CONTENT_SCALE*arVehicleScaleFactor)}}const simulationReady=!isARExperience||(inAR&&arManager.isPlaced());if(simulationReady){updateWorld(world,contactListener,dt);if(isARExperience&&activeARMode!=='free'){const p=sphereBody.position,v=sphereBody.motionProperties.linearVelocity;rigidBody.setPosition(world,sphereBody,[p[0],vehicle.spawnPos.y,p[2]],false);rigidBody.setLinearVelocity(world,sphereBody,[v[0],0,v[2]])}vehicle.update(dt,input);if((isWebArena||(inAR&&activeARMode==='arena'))&&arenaAIDrivers.length)updateArenaAI(arenaAIDrivers,dt,DRIFT_ARENA_RADIUS)}dirLight.position.set(vehicle.spherePos.x+11.4,15,vehicle.spherePos.z-5.3);const mv=vehicle.modelVelocity;_camLead.set(0,0,1).applyQuaternion(vehicle.container.quaternion).multiplyScalar(Math.hypot(mv.x,mv.z));if(!inAR)cam.update(dt,vehicle.spherePos,_camLead);if(simulationReady){particles.update(dt,vehicle);const markScale=isARExperience?AR_CONTENT_SCALE*arVehicleScaleFactor:1,fadingARMarks=isARExperience&&(activeARMode==='free'||activeARMode==='arena');driftMarks.update(dt,vehicle,{scale:markScale,fadeDuration:fadingARMarks?9:null});audio.setRoadRunnerMode(Boolean(roadRunnerVisual&&roadRunnerVisual.visible));audio.update(dt,vehicle.linearSpeed/MAX_SPEED,input.z,vehicle.driftIntensity);const hasInput=input.touchActive||Math.abs(input.x)>.05||Math.abs(input.z)>.05||input.handbrake;if(lapTimer)lapTimer.update(dt,vehicle.spherePos,hasInput)}if(composer&&!inAR)composer.render();else renderer.render(scene,inAR?renderer.xr.getCamera():cam.camera)})
}
init();
